# Site settings
title: Sheeeeep的菜园子
motto: 我把问题寄放在命运那里，上帝保佑热爱生活的人
email: caoyangx2015@163.com
url: "https://github.com/sheeeeep" # the base hostname & protocol for your site
github_username:  Sheeeeep

# Build settings
markdown: kramdown
